### ISSUE TITLE
testing data no found : UrbanRandomSubset

### ISSUE THREAD

**Issue by bciezah1** [dzhakparov/GeneSelectR#11]
Dear dzhakparov,

I hope this message you well. I have installed your tool, and everything looks fine. However, when I tried to load the data (UrbanRandomSubset) in the tutorial, it says it is not found. I tried to look for it in google, but I could not find it. Can you help me with this? Maybe you can share it.

Thank you,

> data("UrbanRandomSubset")
Warning message:
In data("UrbanRandomSubset") : data set ‘UrbanRandomSubset’ not found
> # toy data
> data("UrbanRandomSubset")
Warning message:
In data("UrbanRandomSubset") : data set ‘UrbanRandomSubset’ not found

**Comment by dzhakparov** [comment]
Hi, 
Thanks for the message. 
The toy data has been removed for CRAN release, but you still can access it in the fixtures folder of the package: `GeneSelectR/tests/testthat/fixtures/UrbanRandomSubset.rda ` 
Let me know if you have any other questions. 
Best,
Damir

**Comment by bciezah1** [comment]
You are right, thanks!

**Comment by yxywalab** [comment]
Why I even dont have fixtures folder in my geneselectR packages，I just find a 1 KB file in extra folder.

**Comment by dzhakparov** [comment]
> Why I even dont have fixtures folder in my geneselectR packages，I just find a 1 KB file in extra folder.

Hi, 
You can also find it here in the[ repository](https://github.com/dzhakparov/GeneSelectR/blob/master/tests/testthat/fixtures/UrbanRandomSubset.rda).

**Comment by yxywalab** [comment]
I find it. Thank you very much for your assistance！
