### ISSUE TITLE
upset_upet function not working

### ISSUE THREAD

**Issue by bciezah1** [dzhakparov/GeneSelectR#12]
Hi again,

The tutorial is working pretty well, thanks for the nice work and for response super-fast, I do appreciate it. I was following the tutorial, and everything was working ok till I try the upset_upet plot (see below). I was wondering if I may be missing something. I did not do any change to the code; I am still testing the tool using the testig data you shared.

Best,

> upset_upet(selection_results)
Error in upset_upet(selection_results) : 
  could not find function "upset_upet"

**Comment by dzhakparov** [comment]
Hi, 
Thanks a lot for pointing this out, there is a typo there, it should be: 
`plot_upset(selection_results)` 
This should normally work. 

Best,

**Comment by bciezah1** [comment]
Done, yes, it is working now.
Thanks!!
