### ISSUE TITLE
Cannot plot all of metrics

### ISSUE THREAD

**Issue by thomaskywalker** [dzhakparov/GeneSelectR#13]
Hi,
Great project! I'm trying this workflow on my own data with 5 categories. When I plotted my selection_results with "plot_metrics(selection_results)", only the CV mean score was shown, then I checked "selection_results$test_metrics" and found it an empty list. Below are my script for the selection_results, can you show me how to get the rest of the metrics?
`selection_results <- GeneSelectR::GeneSelectR(
    X = X,
    y = y,
    njobs = -1,
    search_type = "bayesian",
    calculate_permutation_importance = TRUE
)`

Hope this message finds you well, thanks again for your work

**Comment by dzhakparov** [comment]
> Hi, Great project! I'm trying this workflow on my own data with 5 categories. When I plotted my selection_results with "plot_metrics(selection_results)", only the CV mean score was shown, then I checked "selection_results$test_metrics" and found it an empty list. Below are my script for the selection_results, can you show me how to get the rest of the metrics? `selection_results <- GeneSelectR::GeneSelectR( X = X, y = y, njobs = -1, search_type = "bayesian", calculate_permutation_importance = TRUE )`
> 
> Hope this message finds you well, thanks again for your work

Hi, 
Did you manage to fix the error? Would you have a minimal reproducible example so that I can help you out? 
Best,
Damir
