### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yh1028** [dzhakparov/GeneSelectR#14]
_Hello！
I'm getting an error report while using it. But I don't know what the problem is. The error message is as follows：__

> selection_results <- GeneSelectR(X = X, y = y,njobs = -1) # all cores will be used used
Performing feature selection procedure. Please wait, it takes some time
Fitting the data split: 1 
Fitting pipeline for Lasso feature selection method
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
$classifier__n_estimators
[1] 100 500 900

$classifier__max_depth
[1] 10 20 30 40 50

$classifier__min_samples_split
[1]  2  5 10

$classifier__min_samples_leaf
[1] 1 2 4

$classifier__max_features
[1] "auto" "sqrt"

Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-19: ordinal not in range(128)
Run `reticulate::py_last_error()` for details.

How do I end this error?
“UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-19: ordinal not in range(128)”

_Very much appreciated_

**Comment by dzhakparov** [comment]
Hi, 
Thanks a lot for your report. 
Could you please share a minimal reproducible example / data snippet that causes the issue? 
In the meantime, please, check if there are some non-standard characters either in column names or row names. 
Best,
