### ISSUE TITLE
GeneSelectR does not work

### ISSUE THREAD

**Issue by sugarballer** [dzhakparov/GeneSelectR#18]
> load("~/code/GeneSelectR/UrbanRandomSubset.rda")
> head(UrbanRandomSubset[,1:10])
        treatment ENSG00000174371__EXO1 ENSG00000123600__METTL8
CA002YF  Urban_AD          2.984508e+00            1.816292e+00
CA009ST  Urban_AD           0.565690377             2.010920739
CA010EB  Urban_AD          3.6708983671            3.1615995794
CA011LQ  Urban_AD          1.408499e+00            2.674512e+00
CA014LB  Urban_AD          2.5183409223            1.8185148529
CA015AM  Urban_AD          2.6664729139            3.0494281366
        ENSG00000154124__OTULIN ENSG00000006607__FARP2
CA002YF            4.959833e+00           4.125659e+00
CA009ST             4.601555569            4.873391176
CA010EB            4.6202078459           4.8954199262
CA011LQ            3.909325e+00           3.852403e+00
CA014LB            3.8273512783           4.6382172341
CA015AM            4.4946295998           4.4197758295
        ENSG00000135686__KLHL36 ENSG00000130348__QRSL1
CA002YF            6.584945e+00           4.298858e+00
CA009ST             6.677867796            4.043031406
CA010EB            6.0682238886           4.4417887589
CA011LQ            6.041770e+00           4.185302e+00
CA014LB            6.3209867192           4.3729324835
CA015AM            5.9998300955           4.6819749406
        ENSG00000268041__AC010616.1 ENSG00000163812__ZDHHC3
CA002YF                3.150753e+00            4.617841e+00
CA009ST                 3.090960290             5.161640677
CA010EB                3.3511595489            4.9131957592
CA011LQ                3.049633e+00            5.061451e+00
CA014LB                2.6071577494            5.1488088821
CA015AM                2.6885696358            5.0960550151
        ENSG00000233041__PHGR1
CA002YF          -2.934457e+00
CA009ST           -2.934457404
CA010EB          -2.9344574043
CA011LQ          -2.318961e+00
CA014LB          -2.9344574043
CA015AM          -2.9344574043
> X <- UrbanRandomSubset %>% dplyr::select(-treatment) # get the feature matrix
> y <- UrbanRandomSubset$treatment
> y <- as.factor(y)
> y <- as.integer(y)
> y <- as.vector(y)
> class(y)
[1] "integer"
> selection_results <- GeneSelectR::GeneSelectR(X = X, 
+                                               y = y,
+                                               njobs = -1) # all cores will be used
Performing feature selection procedure. Please wait, it takes some time
Fitting the data split: 1 
Fitting pipeline for Lasso feature selection method
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
ValueError: Found input variables with inconsistent numbers of samples: [1000, 60]
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/huangzongwei/miniconda3/envs/GeneSelectR_env/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/home/huangzongwei/miniconda3/envs/GeneSelectR_env/lib/python3.9/site-packages/sklearn/model_selection/_split.py", line 2657, in train_test_split
    arrays = indexable(*arrays)
  File "/home/huangzongwei/miniconda3/envs/GeneSelectR_env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 514, in indexable
    check_consistent_length(*result)
  File "/home/huangzongwei/miniconda3/envs/GeneSelectR_env/lib/python3.9/site-packages/sklearn/utils/validation.py", line 457, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [1000, 60]

── R Traceback ─────────────────────────────────────────────────────────
    ▆
 1. └─GeneSelectR::GeneSelectR(X = X, y = y, njobs = -1)
 2.   └─GeneSelectR::split_data(...)
 3.     └─modules$model_selection$train_test_split(X, y, test_size = test_size)
 4.       └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)

**Comment by sugarballer** [comment]
> Hi, Thanks for your message. Could you please share your configuration as well as the setup of GeneSelectR_env? Best,

[GeneSelectR_env.zip](https://github.com/dzhakparov/GeneSelectR/files/15284768/GeneSelectR_env.zip)
name: GeneSelectR_env
channels:
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=hc881cc4_6
  - libgomp=13.2.0=hc881cc4_6
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.45.3=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4.20240210=h59595ed_0
  - openssl=3.2.1=hd590300_1
  - pip=24.0=pyhd8ed1ab_0
  - python=3.9.19=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=69.5.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024a=h0c530f3_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - boruta==0.3
      - joblib==1.4.0
      - numpy==1.26.4
      - packaging==24.0
      - pyaml==24.4.0
      - pyyaml==6.0.1
      - scikit-learn==1.4.2
      - scikit-optimize==0.10.1
      - scipy==1.13.0
      - threadpoolctl==3.4.0
prefix: /home/huangzongwei/miniconda3/envs/GeneSelectR_env

**Comment by dzhakparov** [comment]
As I can tell your environment has newer versions of the packages,namelt scikit-learn and numpy. 
You can manually install the environment with running: 
 ```
python_packages = c("numpy <= 1.19",
                        "scikit-learn <= 0.22.1",
                        'pandas',
                        "boruta_py",
                        'scikit-optimize')

    # Create the conda environment
    reticulate::conda_create(env_name,
                             python_version = '3.8',
                             packages = python_packages,
                             channel = 'conda-forge')
```
Best,

**Comment by sugarballer** [comment]
> As I can tell your environment has newer versions of the packages,namelt scikit-learn and numpy. You can manually install the environment with running:
> 
> ```
> python_packages = c("numpy <= 1.19",
>                        "scikit-learn <= 0.22.1",
>                        'pandas',
>                        "boruta_py",
>                        'scikit-optimize')
> 
>    # Create the conda environment
>    reticulate::conda_create(env_name,
>                             python_version = '3.8',
>                             packages = python_packages,
>                             channel = 'conda-forge')
> ```
> 
> Best,

Finally it worked, thank you very much.

**Comment by sugarballer** [comment]
Thank you very much, this method is very good, I would like to ask if you will launch a module with survival time in the future

**Comment by dzhakparov** [comment]
Thanks for your kind feedback! 
For the upcoming plans I am going to concentrate on working further on GeneSelectR.
