### ISSUE TITLE
result is not the same as vignettes

### ISSUE THREAD

**Issue by tutu256** [dzhakparov/GeneSelectR#21]
hi! I install docker and run it. but I am not sure whether the code run correctly. when I used the UrbanRandomSubset data to run the pipline, the figures were different, and genes selected were different.

**Comment by dzhakparov** [comment]
Hi! 
It's great that you managed to run everything :) 
The fact that it looks very different is expected: these 1000 genes were selected randomly with most of them being non-informative, moreover there is a certain degree of stochasticity in how feature selection works. So it's totally normal to have a different picture that the one in vignette.
Best,
