### ISSUE TITLE
random_state unused argument

### ISSUE THREAD

**Issue by abedkurdi** [dzhakparov/GeneSelectR#22]
Hello there,

I am using the docker version of this package and I am following the tutorial. When trying to run the following block of code:
```
selection_results <- GeneSelectR::GeneSelectR(X = X, 
                                              y = y,
                                              njobs = -1,
                                              search_type = 'grid')
```

I am getting `unused argument (random_state = random_state)`.

It seems `random_state` is not defined as an argument in this function.

Any work around?

Thank you.

**Comment by dzhakparov** [comment]
Hi, 
Thank you so much for pointing this out, there was a bug indeed. 
It is fixed now for the github version. Please, run: `remotes::install_github(dzhakparov/GeneSelectR)` in the Docker session to update the package. 
I will update the Docker image later and the CRAN version this week. 
Please, let me know how it works. 

Best,

**Comment by abedkurdi** [comment]
Thank you very much, it worked!
